//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDam.Datos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservorio
    {
        public int idReserva { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public int tipoHab { get; set; }
        public System.DateTime fechaEntrada { get; set; }
        public int dias { get; set; }
        public double precio { get; set; }
        public Nullable<bool> desayuno { get; set; }
        public Nullable<bool> garaje { get; set; }
        public string comentarios { get; set; }
        public Nullable<int> idResOnline { get; set; }
    
        
    }

    
}
